# Generated by Django 4.1.5 on 2023-01-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_student_remove_author_semester'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AddField(
            model_name='author',
            name='semester',
            field=models.CharField(choices=[('frontend', 'frontend'), ('backend', 'backend'), ('fullstack', 'fullstack')], default='1', max_length=20),
        ),
    ]
