# Generated by Django 4.1.5 on 2023-01-30 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_delete_student_author_semester'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='semester',
            new_name='genre',
        ),
    ]
