# Generated by Django 4.1.5 on 2023-02-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_semester_author_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='genre',
            field=models.CharField(choices=[('frontend', 'frontend'), ('backend', 'backend'), ('fullstack', 'fullstack')], default='fullstack', max_length=20),
        ),
    ]
